apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: calatrava-tap-workshop
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/ndwinton/calatrava-tap-workshop
  content:
    #image: quay.io/eduk8s/calatrava-tap-workshop:master
    files: github.com/ndwinton/calatrava-tap-workshop#main
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
