apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: calatrava-tap-workshop
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 60m
  url: https://github.com/ndwinton/calatrava-tap-workshop
  content:
    image: harbor-repo.vmware.com/nwinton/calatrava-tap-workshop:latest
    files: "github.com/ndwinton/calatrava-tap-workshop?ref=main"
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
